### ISSUE TITLE
"Invalid Application-ID or API key"

### ISSUE THREAD

**Issue by L0garithmic** [NicoWeio/blinkist#6]
https://p3sczpah8s-dsn.algolia.net/1/indexes/books-production/query

This shows "Invalid Application-ID or API key"
Is this normal or has this stopped working?
If this has stopped working, how do we host our own version?

**Comment by NicoWeio** [comment]
Thank you for bringing this to my attention. I did not know what reliability to expect when I included the search feature. Now, this is the first time it fails (to my knowledge). 
Maybe all that needs to be done is to inspect a fresh request and extract a new API key.
I'll have a look soon-ish.

**Comment by NicoWeio** [comment]
Thank you for bringing this to my attention. I did not know what reliability to expect when I included the search feature. Now, this is the first time it fails (to my knowledge). 
Maybe all that needs to be done is to inspect a fresh request and extract a new API key.
I'll have a look soon-ish.

**Comment by L0garithmic** [comment]
I am not positive that is the issue to begin with. I am trying to download books and they seem to be failing. It's almost like Blinkist disabled their API. So I was digging and realized this was not working. Maybe it's not even the issue. I am just amazed you are still active in replying. Thank you for that!

**Comment by NicoWeio** [comment]
Wait, you just opened [p3sczpah8s-dsn.algolia.net/1/indexes/books-production/query](https://p3sczpah8s-dsn.algolia.net/1/indexes/books-production/query) in your browser and got this message? 
That's perfectly normal, as you'd need to set these HTTP headers:
```python
'x-algolia-api-key': '1a09a41ec4e8624c821ac861d8fa8fe1',
'x-algolia-application-id': 'P3SCZPAH8S',
```
Using `./main.py . --search Test` works as expected for me.

If that doesn't solve your issue, could you maybe post some output of `main.py` failing?

On a side note, `--freecurated` seems to no longer work; this is also shown in my automated tests.

**Comment by L0garithmic** [comment]
It's working now. Seems Blinkist's API was down for a few hours. Weird. Thank you!
